FROM alpine:latest

RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY ./.bin/app .
COPY ./configs/config.yml ./configs/config.yml
COPY ./lang/json/*.json ./lang/json/

EXPOSE 8000

CMD ["./app"]