apiVersion: v1
kind: PersistentVolume
metadata:
  name: boltdb
spec:
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: boltdb-storage
  local:
    path: {{ .Values.persistentVolume.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              {{- with .Values.persistentVolume.nodeAffinity.hostname }}
              values:
                {{- toYaml . | nindent 16 }}
              {{- end }}
