apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boltdb
spec:
  storageClassName: boltdb-storage
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
