replicaCount: 1
image:
  repository: alice-checklist
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: regcred
nameOverride: "alice-checklist"
fullnameOverride: "alice-checklist"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels:
  app: alice-checklist

podSecurityContext: {}
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  create: true
  type: ClusterIP
  externalPort: 80
  internalPort: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: alice.gohome.run
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
#    - hosts:
#        - alice.gohome.run
#      secretName: alice-gohome-run-tls
  email: skubach@tut.by

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

#livenessProbe:
#  httpGet:
#    path: /
#    port: http
#readinessProbe:
#  httpGet:
#    path: /
#    port: http

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  type: RollingUpdate

volumes:
  - name: googlekeep
    secret:
      secretName: googlekeep
  - name: db
    persistentVolumeClaim:
      claimName: boltdb
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

volumeMounts:
  - name: db
    mountPath: /root/db
  - name: googlekeep
    mountPath: /root/configs/googlekeep
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

persistentVolume:
  path: /home/skubach/alice-checklist/db
  nodeAffinity:
    hostname:
      - node1.internal
  storage: 5Mi

storageClass:
  create: true
